### ISSUE TITLE
Snippets appear not to be loading

### ISSUE THREAD

**Issue by scarolan** [darron/language-chef#3]
Hi Darron, took this for a spin this morning.  I installed the package ok, but none of the snippets appear to be working.  Any special configs required?

**Comment by grosendorf** [comment]
I'm having this issue as well, anybody have any insight?

**Comment by tknerr** [comment]
Here too. No insights yet, but maybe worth checking this:
https://atom.io/docs/v0.186.0/creating-a-package#snippets

**Comment by tknerr** [comment]
Heads up: the snippets work once the file you are editing is correctly being detected as a "Chef" file. Typically, that's the case for me at least, `*.rb` files are opened with the "Ruby" grammar by default. 

So if it is a Chef recipe that you are editing you have to manually set the grammar to "Chef" via the [builtin grammar selector](https://github.com/atom/grammar-selector) (hint: `Ctrl + Shift + L` will open it)

**Comment by darron** [comment]
Yes - that's likely the key - this does work when it's set to `Chef`.

Thanks for the report - sorry I didn't see the issue.
